# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aiframe/FrameInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FrameInfo(genpy.Message):
  _md5sum = "a063fad8d840316d2176ad9da1ad45fc"
  _type = "aiframe/FrameInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool detected
bool tracked
int64 detect_seq
int64 track_seq
float32[] detect_results
float32[] track_results"""
  __slots__ = ['detected','tracked','detect_seq','track_seq','detect_results','track_results']
  _slot_types = ['bool','bool','int64','int64','float32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       detected,tracked,detect_seq,track_seq,detect_results,track_results

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FrameInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.detected is None:
        self.detected = False
      if self.tracked is None:
        self.tracked = False
      if self.detect_seq is None:
        self.detect_seq = 0
      if self.track_seq is None:
        self.track_seq = 0
      if self.detect_results is None:
        self.detect_results = []
      if self.track_results is None:
        self.track_results = []
    else:
      self.detected = False
      self.tracked = False
      self.detect_seq = 0
      self.track_seq = 0
      self.detect_results = []
      self.track_results = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2q().pack(_x.detected, _x.tracked, _x.detect_seq, _x.track_seq))
      length = len(self.detect_results)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.detect_results))
      length = len(self.track_results)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.track_results))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.detected, _x.tracked, _x.detect_seq, _x.track_seq,) = _get_struct_2B2q().unpack(str[start:end])
      self.detected = bool(self.detected)
      self.tracked = bool(self.tracked)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.detect_results = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.track_results = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2q().pack(_x.detected, _x.tracked, _x.detect_seq, _x.track_seq))
      length = len(self.detect_results)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.detect_results.tostring())
      length = len(self.track_results)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.track_results.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.detected, _x.tracked, _x.detect_seq, _x.track_seq,) = _get_struct_2B2q().unpack(str[start:end])
      self.detected = bool(self.detected)
      self.tracked = bool(self.tracked)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.detect_results = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.track_results = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2q = None
def _get_struct_2B2q():
    global _struct_2B2q
    if _struct_2B2q is None:
        _struct_2B2q = struct.Struct("<2B2q")
    return _struct_2B2q
